M48
; DRILL file {KiCad 8.0.2} date 2024-07-10T14:47:39-0400
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-10T14:47:39-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X2.0866Y-1.0669
X2.0945Y-2.5433
X4.6378Y-1.0669
X4.6457Y-2.5394
M30
